/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f1xx.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void Delay (uint32_t time);

int main(void)
{
	// Set IOPB EN
	RCC->APB2ENR |= (1 << 3); // Enable GPIOB clock

	// Set MODE12[1:0] = 01: : Output mode, max speed 10 MHz
	GPIOB->CRH |= (1 << 16); // set bit 16
	GPIOB->CRH &= ~(1 << 17); // clear bit 17

	// Clear  CNF12[1:0]: General purpose output push-pull
	GPIOB->CRH &= ~(0b11 << 18);

    /* Loop forever */
	for(;;)
	{
//		// Opt 1: BSSR
//		// Set GPIOB Pin 12
//		GPIOB->BSRR |= (1 << 12);
//		Delay (10000000);  // random delay
//		// Reset GPIOB Pin 12
//		GPIOB->BSRR |= (1 << 28);
//		Delay (10000000);  // random delay

//		// Opt 2: ODR
//		// Set GPIOB Pin 12
//		GPIOB->ODR |= (1 << 12);
//		Delay (10000000);  // random delay
//
//		// Reset GPIOB Pin 12
//		GPIOB->ODR &= ~(1 << 12);
//		Delay (10000000);  // random delay

	}
}

void Delay (uint32_t time)
{
	while (time--);
}
